# Documentation of server configuration attributes:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.application-properties.server
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  session-token: ${AWS_SESSION_TOKEN}
  student-bucket-name: hcervera-uady-aws-final-project-s3-bucket-1
